[package]
name = "learning-rust-multithreaded-async"
version = "0.1.0"
edition = "2021"

[dependencies]
sprintf = "0.4.0"
tokio = { version = "1", features = ["full"] }
trust-dns-resolver = "0.23.2"
url = "2.5.4"

