[package]
name = "multithreaded-async"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std-resolver = "0.24.2"
tokio = { workspace = true }
tokio-rustls = "0.26.1"
url = "2.5.4"
webpki-roots = "0.26.7"

