[workspace]
resolver = "1"

members = [ 
<<<<<<< HEAD
    "crates/multithreaded-async"
, "crates/webapp"]
=======
    "crates/multithreaded-async",
    "crates/webapp"
]
>>>>>>> 772d9bd (.)


[workspace.dependencies]
tokio = { version = "1.21.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
