[workspace]
resolver = "1"

members = [ 
    "crates/multithreaded-async"
, "crates/webapp"]


[workspace.dependencies]
tokio = { version = "1.21.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
