[package]
name = "sfmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
<<<<<<< HEAD
proc-macro2 = "1.0.92"
=======
darling = "0.20.10"
>>>>>>> 6aece98 (.)
quote = "1.0.38"
syn = {version = "2.0.95", features = ["full"]}
trybuild = "1.0.101"
